name: Build PDF

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install LaTeX
        run: sudo apt-get install -y texlive-full

      - name: Compile LaTeX document
        run: pdflatex -output-directory docs cv_english_andreamontes.tex

      - name: Upload PDF to GitHub Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cv_english_andreamontes
          path: docs/cv_english_andreamontes.pdf

      - name: Commit PDF
        run: |
          git config --global user.name 'mamontesp'
          git config --global user.email 'mamontesp@gmail.com'
          git checkout gh-pages  # Switch to the branch GitHub Pages is set to build from
          git add -f docs/cv_english_andreamontes.pdf
          git commit -m "Update PDF"
          git push  # Push changes to the same branch GitHub Pages is set to build from
