name: Build CV in PDF
on:
  push:
    branches:
      - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
# Sets permissions of the GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags
          persist-credentials: false

      - name: Calculate cache key
        id: cache-key
        run: echo "CACHE_KEY=$(sha256sum cv_english_andreamontes.tex | cut -d' ' -f1)" >> $GITHUB_ENV

      - name: Restore PDF from cache
        id: cache 
        uses: actions/cache@v3
        with:
          path: docs/assets/cv/cv_english_andreamontes.pdf
          key: ${{ env.CACHE_KEY }}

      - name: Check cache hit status
        run: |
          echo "Cache hit: ${{ steps.cache.outputs.cache-hit }}"
          ls -la docs/assets/cv/

      - name: Install LaTeX
        if: steps.cache.outputs.cache-hit != 'true'
        run: sudo apt-get install -y texlive-full

      - name: Compile LaTeX document
        if: steps.cache.outputs.cache-hit != 'true'
        run: pdflatex -output-directory docs/assets/cv cv_english_andreamontes.tex

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build Jekyll site
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
          destination: ./_site

      - name: Upload site and CV
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4